Enabled: true
CommandAliases: []
World:
  WorldName: ShieldPVP
  Spacing: 500
Schematics:
  schem1:
    File: map.schem
    #X,Y,Z,Yaw,Pitch
    SpawnLocations:
      - 0 100 0 0 0
      - -10 100 0 0 0