Enabled: true
CommandAliases: []
BowWorld:
  World: BowAimWorld
  Spacing: 500
Schematics:
  schem1:
    File: bowAim1.schem
    PlayerSpawnLocations:
      - 0 100 0 0 0
    BlockSpawnLocations:
      - 20 110 20 30 120 30
      - 50 120 50 60 130 60
    NumberOfBlocks: 5
    BlockMaterials:
      - TARGET